In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('../Data/External/1000_movies_data.csv')
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
21,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
23,24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
24,25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
25,26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
28,29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
29,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
971,972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
972,973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
974,975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
975,976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
976,977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
977,978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
979,980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
982,983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
984,985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
985,986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [5]:
df['Votes'].max()

1791916

In [40]:
df[df['Director']=='Christopher Nolan']['Genre'].unique()

array(['Adventure,Drama,Sci-Fi', 'Action,Crime,Drama',
       'Drama,Mystery,Sci-Fi', 'Action,Adventure,Sci-Fi',
       'Action,Thriller'], dtype=object)

In [6]:
df['Revenue (Millions)'].max()

936.63

In [7]:
df.groupby('Genre')['Genre'].unique()

Genre
Action                                            [Action]
Action,Adventure                        [Action,Adventure]
Action,Adventure,Biography    [Action,Adventure,Biography]
Action,Adventure,Comedy          [Action,Adventure,Comedy]
Action,Adventure,Crime            [Action,Adventure,Crime]
Action,Adventure,Drama            [Action,Adventure,Drama]
Action,Adventure,Family          [Action,Adventure,Family]
Action,Adventure,Fantasy        [Action,Adventure,Fantasy]
Action,Adventure,Horror          [Action,Adventure,Horror]
Action,Adventure,Mystery        [Action,Adventure,Mystery]
Action,Adventure,Romance        [Action,Adventure,Romance]
Action,Adventure,Sci-Fi          [Action,Adventure,Sci-Fi]
Action,Adventure,Thriller      [Action,Adventure,Thriller]
Action,Adventure,Western        [Action,Adventure,Western]
Action,Biography,Crime            [Action,Biography,Crime]
Action,Biography,Drama            [Action,Biography,Drama]
Action,Comedy                              [Action,Comedy]
Action,Comedy,Crime                  [Action,Comedy,Crime]
Action,Comedy,Drama                  [Action,Comedy,Drama]
Action,Comedy,Family                [Action,Comedy,Family]
Action,Comedy,Fantasy              [Action,Comedy,Fantasy]
Action,Comedy,Horror                [Action,Comedy,Horror]
Action,Comedy,Mystery              [Action,Comedy,Mystery]
Action,Comedy,Romance              [Action,Comedy,Romance]
Action,Comedy,Sci-Fi                [Action,Comedy,Sci-Fi]
Action,Comedy,Sport                  [Action,Comedy,Sport]
Action,Crime,Drama                    [Action,Crime,Drama]
Action,Crime,Fantasy                [Action,Crime,Fantasy]
Action,Crime,Mystery                [Action,Crime,Mystery]
Action,Crime,Sci-Fi                  [Action,Crime,Sci-Fi]
                                          ...
Drama,Romance,Sci-Fi                [Drama,Romance,Sci-Fi]
Drama,Romance,Thriller            [Drama,Romance,Thriller]
Drama,Romance,War                      [Drama,Romance,War]
Drama,Sci-Fi                                [Drama,Sci-Fi]
Drama,Sci-Fi,Thriller              [Drama,Sci-Fi,Thriller]
Drama,Sport                                  [Drama,Sport]
Drama,Thriller                            [Drama,Thriller]
Drama,Thriller,War                    [Drama,Thriller,War]
Drama,War                                      [Drama,War]
Drama,Western                              [Drama,Western]
Fantasy,Horror                            [Fantasy,Horror]
Fantasy,Horror,Thriller          [Fantasy,Horror,Thriller]
Fantasy,Mystery,Thriller        [Fantasy,Mystery,Thriller]
Horror                                            [Horror]
Horror,Mystery                            [Horror,Mystery]
Horror,Mystery,Sci-Fi              [Horror,Mystery,Sci-Fi]
Horror,Mystery,Thriller          [Horror,Mystery,Thriller]
Horror,Sci-Fi,Thriller            [Horror,Sci-Fi,Thriller]
Horror,Thriller                          [Horror,Thriller]
Mystery,Romance,Sci-Fi            [Mystery,Romance,Sci-Fi]
Mystery,Romance,Thriller        [Mystery,Romance,Thriller]
Mystery,Sci-Fi,Thriller          [Mystery,Sci-Fi,Thriller]
Mystery,Thriller                        [Mystery,Thriller]
Mystery,Thriller,Western        [Mystery,Thriller,Western]
Romance,Sci-Fi                            [Romance,Sci-Fi]
Romance,Sci-Fi,Thriller          [Romance,Sci-Fi,Thriller]
Sci-Fi                                            [Sci-Fi]
Sci-Fi,Thriller                          [Sci-Fi,Thriller]
Thriller                                        [Thriller]
Thriller,War                                [Thriller,War]
Name: Genre, Length: 207, dtype: object

In [8]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [9]:
df['Rating'].unique()

array([8.1, 7. , 7.3, 7.2, 6.2, 6.1, 8.3, 6.4, 7.1, 7.5, 7.8, 7.9, 7.7,
       6.6, 8.2, 6.7, 8. , 6.5, 5.3, 6.8, 4.7, 5.9, 6.3, 5.6, 8.6, 7.6,
       6.9, 2.7, 3.7, 5.8, 9. , 7.4, 4.1, 8.5, 8.8, 5.4, 6. , 5.7, 8.4,
       5.2, 5.5, 4.8, 3.9, 4.9, 5.1, 5. , 4.3, 4.6, 4.2, 4. , 3.2, 4.5,
       1.9, 3.5, 4.4])

In [24]:
df['Rating'].median()

6.8

In [25]:
df['Rating'].max()

9.0

In [11]:
df['Year'].unique().sort()

In [12]:
df['Year'].unique()

array([2014, 2012, 2016, 2015, 2007, 2011, 2008, 2006, 2009, 2010, 2013],
      dtype=int64)

In [13]:
years = df['Year'].unique().sort()

In [15]:
years

In [16]:
 df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [17]:
df['Director'].count()

1000

In [18]:
directors = df['Director'].unique()

In [19]:
directors.sort()

In [20]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [17]:
df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [18]:
df[(df['Rank']<1001) & (df['Year'] < 2010)].count()[['Title', 'Year', 'Genre', 'Revenue (Millions)']]

Title                 200
Year                  200
Genre                 200
Revenue (Millions)    189
dtype: int64

In [19]:
imdb = pd.read_csv('../Data/External/IMDB-Movie-Data.csv')
imdb

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
10,11,Fantastic Beasts and Where to Find Them,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0
11,12,Hidden Figures,"Biography,Drama,History",The story of a team of female African-American...,Theodore Melfi,"Taraji P. Henson, Octavia Spencer, Janelle Mon...",2016,127,7.8,93103,169.27,74.0
12,13,Rogue One,"Action,Adventure,Sci-Fi",The Rebel Alliance makes a risky move to steal...,Gareth Edwards,"Felicity Jones, Diego Luna, Alan Tudyk, Donnie...",2016,133,7.9,323118,532.17,65.0
13,14,Moana,"Animation,Adventure,Comedy","In Ancient Polynesia, when a terrible curse in...",Ron Clements,"Auli'i Cravalho, Dwayne Johnson, Rachel House,...",2016,107,7.7,118151,248.75,81.0
14,15,Colossal,"Action,Comedy,Drama",Gloria is an out-of-work party girl forced to ...,Nacho Vigalondo,"Anne Hathaway, Jason Sudeikis, Austin Stowell,...",2016,109,6.4,8612,2.87,70.0
15,16,The Secret Life of Pets,"Animation,Adventure,Comedy",The quiet life of a terrier named Max is upend...,Chris Renaud,"Louis C.K., Eric Stonestreet, Kevin Hart, Lake...",2016,87,6.6,120259,368.31,61.0
16,17,Hacksaw Ridge,"Biography,Drama,History","WWII American Army Medic Desmond T. Doss, who ...",Mel Gibson,"Andrew Garfield, Sam Worthington, Luke Bracey,...",2016,139,8.2,211760,67.12,71.0
17,18,Jason Bourne,"Action,Thriller",The CIA's most dangerous former operative is d...,Paul Greengrass,"Matt Damon, Tommy Lee Jones, Alicia Vikander,V...",2016,123,6.7,150823,162.16,58.0
18,19,Lion,"Biography,Drama",A five-year-old Indian boy gets lost on the st...,Garth Davis,"Dev Patel, Nicole Kidman, Rooney Mara, Sunny P...",2016,118,8.1,102061,51.69,69.0
19,20,Arrival,"Drama,Mystery,Sci-Fi",When twelve mysterious spacecraft appear aroun...,Denis Villeneuve,"Amy Adams, Jeremy Renner, Forest Whitaker,Mich...",2016,116,8.0,340798,100.50,81.0
20,21,Gold,"Adventure,Drama,Thriller","Kenny Wells, a prospector desperate for a luck...",Stephen Gaghan,"Matthew McConaughey, Edgar Ramírez, Bryce Dall...",2016,120,6.7,19053,7.22,49.0
21,22,Manchester by the Sea,Drama,A depressed uncle is asked to take care of his...,Kenneth Lonergan,"Casey Affleck, Michelle Williams, Kyle Chandle...",2016,137,7.9,134213,47.70,96.0
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
23,24,Trolls,"Animation,Adventure,Comedy","After the Bergens invade Troll Village, Poppy,...",Walt Dohrn,"Anna Kendrick, Justin Timberlake,Zooey Deschan...",2016,92,6.5,38552,153.69,56.0
24,25,Independence Day: Resurgence,"Action,Adventure,Sci-Fi",Two decades after the first Independence Day i...,Roland Emmerich,"Liam Hemsworth, Jeff Goldblum, Bill Pullman,Ma...",2016,120,5.3,127553,103.14,32.0
25,26,Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
26,27,Bahubali: The Beginning,"Action,Adventure,Drama","In ancient India, an adventurous and daring ma...",S.S. Rajamouli,"Prabhas, Rana Daggubati, Anushka Shetty,Tamann...",2015,159,8.3,76193,6.50,NaN
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
28,29,Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.08,60.0
29,30,Assassin's Creed,"Action,Adventure,Drama",When Callum Lynch explores the memories of his...,Justin Kurzel,"Michael Fassbender, Marion Cotillard, Jeremy I...",2016,115,5.9,112813,54.65,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Texas Chainsaw 3D,"Horror,Thriller",A young woman travels to Texas to collect an i...,John Luessenhop,"Alexandra Daddario, Tania Raymonde, Scott East...",2013,92,4.8,37060,34.33,62.0
971,972,Disturbia,"Drama,Mystery,Thriller",A teen living under house arrest becomes convi...,D.J. Caruso,"Shia LaBeouf, David Morse, Carrie-Anne Moss, S...",2007,105,6.9,193491,80.05,NaN
972,973,Rock of Ages,"Comedy,Drama,Musical",A small town girl and a city boy meet on the S...,Adam Shankman,"Julianne Hough, Diego Boneta, Tom Cruise, Alec...",2012,123,5.9,64513,38.51,47.0
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
974,975,Queen of Katwe,"Biography,Drama,Sport",A Ugandan girl sees her world rapidly change a...,Mira Nair,"Madina Nalwanga, David Oyelowo, Lupita Nyong'o...",2016,124,7.4,6753,8.81,73.0
975,976,My Big Fat Greek Wedding 2,"Comedy,Family,Romance",A Portokalos family secret brings the beloved ...,Kirk Jones,"Nia Vardalos, John Corbett, Michael Constantin...",2016,94,6.0,20966,59.57,37.0
976,977,Dark Places,"Drama,Mystery,Thriller",Libby Day was only eight years old when her fa...,Gilles Paquet-Brenner,"Charlize Theron, Nicholas Hoult, Christina Hen...",2015,113,6.2,31634,NaN,39.0
977,978,Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
979,980,The Skin I Live In,"Drama,Thriller","A brilliant plastic surgeon, haunted by past t...",Pedro Almodóvar,"Antonio Banderas, Elena Anaya, Jan Cornet,Mari...",2011,120,7.6,108772,3.19,70.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
982,983,Across the Universe,"Drama,Fantasy,Musical",The music of the Beatles and the Vietnam War f...,Julie Taymor,"Evan Rachel Wood, Jim Sturgess, Joe Anderson, ...",2007,133,7.4,95172,24.34,56.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
984,985,Max,"Adventure,Family",A Malinois dog that helped American Marines in...,Boaz Yakin,"Thomas Haden Church, Josh Wiggins, Luke Kleint...",2015,111,6.8,21405,42.65,47.0
985,986,Your Highness,"Adventure,Comedy,Fantasy","When Prince Fabious's bride is kidnapped, he g...",David Gordon Green,"Danny McBride, Natalie Portman, James Franco, ...",2011,102,5.6,87904,21.56,31.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
990,991,Underworld: Rise of the Lycans,"Action,Adventure,Fantasy",An origins story centered on the centuries-old...,Patrick Tatopoulos,"Rhona Mitra, Michael Sheen, Bill Nighy, Steven...",2009,92,6.6,129708,45.80,44.0
991,992,Taare Zameen Par,"Drama,Family,Music",An eight-year-old boy is thought to be a lazy ...,Aamir Khan,"Darsheel Safary, Aamir Khan, Tanay Chheda, Sac...",2007,165,8.5,102697,1.20,42.0
992,993,Take Me Home Tonight,"Comedy,Drama,Romance","Four years after graduation, an awkward high s...",Michael Dowse,"Topher Grace, Anna Faris, Dan Fogler, Teresa P...",2011,97,6.3,45419,6.92,NaN
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,995,Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [21]:
df[(df['Rank']<101) & (df['Rating'] < 7)].count()[['Title', 'Year', 'Genre', 'Rating']]

Title     35
Year      35
Genre     35
Rating    35
dtype: int64

In [23]:
df.sample(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
492,493,Cloverfield,"Action,Horror,Sci-Fi",A group of friends venture deep into the stree...,Matt Reeves,"Mike Vogel, Jessica Lucas, Lizzy Caplan, T.J. ...",2008,85,7.0,313803,80.03,64.0
171,172,Kubo and the Two Strings,"Animation,Adventure,Family",A young boy named Kubo must locate a magical s...,Travis Knight,"Charlize Theron, Art Parkinson, Matthew McCona...",2016,101,7.9,72778,48.02,84.0
891,892,This Is 40,"Comedy,Romance","Pete and Debbie are both about to turn 40, the...",Judd Apatow,"Paul Rudd, Leslie Mann, Maude Apatow, Iris Apatow",2012,134,6.2,108156,67.52,NaN
108,109,All We Had,Drama,A mother struggles to make a better life for h...,Katie Holmes,"Eve Lindley, Richard Kind, Mark Consuelos, Kat...",2016,105,5.8,1004,NaN,48.0
816,817,I.T.,"Crime,Drama,Mystery","A self-proclaimed millionaire, has his life tu...",John Moore,"Pierce Brosnan, Jason Barry, Karen Moskow, Kai...",2016,95,5.4,8755,NaN,27.0
824,825,Man Down,"Drama,Thriller","In a post-apocalyptic America, former U.S. Mar...",Dito Montiel,"Shia LaBeouf, Jai Courtney, Gary Oldman, Kate ...",2015,90,5.8,4779,NaN,27.0
808,809,A United Kingdom,"Biography,Drama,Romance",The story of King Seretse Khama of Botswana an...,Amma Asante,"David Oyelowo, Rosamund Pike, Tom Felton, Jack...",2016,111,6.8,4771,3.90,65.0
741,742,Hands of Stone,"Action,Biography,Drama",The legendary Roberto Duran and his equally le...,Jonathan Jakubowicz,"Edgar Ramírez, Usher Raymond, Robert De Niro, ...",2016,111,6.6,8998,4.71,54.0
937,938,Super,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0
158,159,Scott Pilgrim vs. the World,"Action,Comedy,Fantasy",Scott Pilgrim must defeat his new girlfriend's...,Edgar Wright,"Michael Cera, Mary Elizabeth Winstead, Kieran ...",2010,112,7.5,291457,31.49,69.0

In [28]:

desc = df.describe()

In [49]:
def categ_on_rat(rate):
    if rate <= desc.loc['min']['Rating']:
        return 'Not watchable'
    elif rate > desc.loc['min']['Rating'] and rate <= desc.loc['25%']['Rating']:
        return 'Not Recommended'
    elif rate > desc.loc['25%']['Rating'] and rate <= desc.loc['50%']['Rating']:
        return 'Below Average'
    elif rate > desc.loc['50%']['Rating'] and rate <= desc.loc['75%']['Rating']:
        return 'Above Average'
    elif rate > desc.loc['75%']['Rating'] and rate <= desc.loc['max']['Rating']:
        return 'Value for Money'

In [46]:
categ_on_rat(4.5)

'Not Recommended'

In [47]:
categ_on_rat(9)

'Value for Money'

In [48]:
categ_on_rat(6.8)

'Below Average'

In [55]:
df['ColumnOnRating'] = df['Rating'].apply(lambda x: categ_on_rat(x))

In [56]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,ColumnOnRating
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,Value for Money
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,Above Average
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,Above Average
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,Above Average
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,Not Recommended

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
Rank                  1000 non-null int64
Title                 1000 non-null object
Genre                 1000 non-null object
Description           1000 non-null object
Director              1000 non-null object
Actors                1000 non-null object
Year                  1000 non-null int64
Runtime (Minutes)     1000 non-null int64
Rating                1000 non-null float64
Votes                 1000 non-null int64
Revenue (Millions)    872 non-null float64
Metascore             936 non-null float64
ColumnOnRating        1000 non-null object
dtypes: float64(3), int64(4), object(6)
memory usage: 101.6+ KB